name: Hamidreza Soleimani's Blog
description: Just about what I know
meta_description: "Hamidreza Soleimani's Blog - Just about what I know"

# markdown: redcarpet
# redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

markdown: kramdown
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
bare_url: 'hamidreza-s.github.io'
url: 'https://hamidreza-s.github.io'
author: 'Hamidreza Soleimani'
author_description: 'I am a human, instrumentalist and a software developer, trying to figure out how to live.'
